# Register Page Locators ::

sila_main_logo = "//*[@id='main-logo']"
signup_to_move_money_heading = "//h1[contains(text(),'Sign up to move money with Sila.')]"
ach_transfer_link = "//a[contains(text(),'ACH Transfer API')]"
redirect_ach_transfer_page_heading = "//p[contains(text(),'Transfer money and initiate ACH transfers fast usi')]"
digital_wallet_api_link = "//a[contains(text(),'Digital Wallet API')]"
redirect_digital_wallet_page_heading = "//p[contains(text(),'Our Wallet API links any U.S. bank account via API')]"
bank_account_linking_api_link = "//a[contains(text(),'Bank Account Linking API')]"
redirect_bank_account_linking_page_heading = "//p[contains(text(),'Link bank accounts and transfer money fast " \
                                              "using t')] "
kyc_kyb_identity_verification_api_link = "//a[contains(text(),'KYC & KYB Identity Verification API')]"
redirect_kyb_kyc_verification_page_heading = "//p[contains(text(),'Banking, Digital Wallet & ACH Payments API " \
                                              "for Sof')] "
already_have_a_sila_account_text = "//p[contains(text(),'Already have a Sila account?')]"
sign_up_link = "//span[contains(text(),'Sign up')]"
login_link = "//span[contains(text(),'Login')]"
login_page_heading = "//h2[contains(text(),'Log-in to the Console.')]"
privacy_link = "//a[contains(text(),'Privacy Policy')]"
redirect_privacy_page_heading = "//h1[contains(text(),'Privacy Policy')]"
terms_of_service_link = "//a[contains(text(),'Terms of Service')]"
redirect_terms_page_heading = "//h1[contains(text(),'Terms of Service')]"
sdk_license_agreement_link = "//a[contains(text(),'SDK License Agreement')]"
redirect_sdk_page_heading = "//h1[contains(text(),'SOFTWARE DEVELOPMENT KIT LICENSE AGREEMENT')]"
first_name_field = "//input[@id='registerForm.first_name']"
surname_field = "//input[@id='registerForm.surname']"
company_name_field = "//body/div[@id='sila-app']/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[" \
                      "1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[1]/div[1]/input[1] "
select_company_name = "//a[@id='registerForm.company_name-item-0']"
work_email_field = "//input[@id='registerForm.email']"
work_phone_field = "//input[@id='registerForm.phone']"
password_field = "//input[@id='registerPasswordForm.password']"
confirm_password_field = "//input[@id='registerPasswordForm.confirmPassword']"
terms_checkbox = "//input[@name='privacy']"
create_account_button = "//button[contains(text(),'Create Account')]"
email_icon = ".email .fas"
invalid_email = "//div[contains(text(),'Invalid email address')]"
max_character_email = "//div[contains(text(),'Maximum of 254 characters.')]"
phone_icon = ".phone:nth-child(4) .fas"
invalid_phone_validation = "//div[contains(text(),'Invalid phone number')]"
password_icon = ".password:nth-child(5) .fas"
confirm_password_icon = ".password:nth-child(6) .fas"
password_min_length_validation = "//div[contains(text(),'Minimum of 8 characters required.')]"
password_max_length_validation = "//div[contains(text(),'Provide a shorter password.')]"
password_mismatch_validation = "//div[contains(text(),'Re-enter your password confirmation so it matches ')]"
password_lookalike_email_validation = '''//div[contains(text(),"Password can't contain your handle or email.")]'''
team_field_heading = "//h2[contains(text(),'Give your team a name.')]"
team_field_label = "//label[contains(text(),'Team Name')]"
add_team_name_field = "//input[@id='InviteTeamMembers.team_name']"
team_name_validation_icon = ".fas"
team_name_already_exists_validation = "//div[contains(text(),'Team name already exists.')]"
add_team_mates_box = "//textarea[@id='InviteTeamMembers.emails']"
send_invites_button = "//button[contains(text(),'Send Invites')]"
invitation_sent_message = "//div[@id='sila-app']/div/div/div/main/div/div/div/div/div/div/div[2]/div/form/div[3]/p"
continue_button = "//button[contains(text(),'Continue')]"
invite_your_team_and_collaborate_heading = "//h3[contains(text(),'Invite your team and collaborate.')]"
listing__text_1 = "//li[contains(text(),'Save time with faster onboarding')]"
listing__text_2 = "//li[contains(text(),'Stay up to date with the latest features')]"
listing_text_3 = "//li[contains(text(),'Organize communication with the Sila team')]"
add_team_box_placeholder_text = "//label[contains(text(),'Add teammates by email address and use commas to s')]"
skip_to_account_button = "// button[contains(text(), 'Skip to account creation')]"
welcome_screen_heading = '''//h1[contains(text(),'Welcome to the Sila Console')]'''
flex_validation_message = "//div[@class='d-flex my-auto p-0 container']"