sign_up_page_title = "Sign Up | Sila API"
login_page_heading = "Log-in to the Console."
invite_team_member_title = "Sila Console - Register::Invite Team Members"
questionnaire_page_title = "Sila Console - Register::Questions"

invalid_email_address = "Invalid email address"
email_more_than_max_length = "Ensure this field has no more than 254 characters."
password_less_than_min_length = "Minimum of 8 characters required."
password_more_than_max_length = "Provide a shorter password."
password_mismatch = "Re-enter your password confirmation so it matches your password."
password_lookalike_message = "Password can't contain your username or email."
invalid_phone_message = "Invalid phone number"
team_heading = "Give your team a name."
team_name_already_exits = "Team name already exists."
already_have_a_sila_account = "Already have a Sila account? Login"
invitation_sent_successfully = "Invites successfully sent!"

#  Heading after page redirect by clicking on links
redirected_privacy_page_heading = "Privacy Policy"
redirected_terms_page_heading = "Terms of Service"
redirected_sdk_agreement_page_heading = "SOFTWARE DEVELOPMENT KIT LICENSE AGREEMENT"
redirected_ach_page_heading = "Transfer money and initiate ACH transfers fast using the Sila API"
redirected_digital_wallet_api_page_heading = "Our Wallet API links any U.S. bank account via API for in-app payments."
redirected_account_linking_page_heading = "Link bank accounts and transfer money fast using the Sila API"
redirected_kyc_kyb_identity_verification_page_heading= "Banking, Digital Wallet & ACH Payments API for Software Teams"